-- liquibase formatted sql
-- changeset liquibase-autogenerated:1733359107750-1
CREATE TABLE article (
    article_id INT AUTO_INCREMENT NOT NULL,
    author_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    `description` VARCHAR(1000) NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP(0) DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(0) NULL,
    CONSTRAINT PK_ARTICLE PRIMARY KEY (article_id)
);
-- changeset liquibase-autogenerated:1733359107750-2
CREATE TABLE article_tag (
    article_id INT NOT NULL,
    tag_id INT NOT NULL,
    CONSTRAINT PK_ARTICLE_TAG PRIMARY KEY (article_id, tag_id)
);
-- changeset liquibase-autogenerated:1733359107750-3
CREATE TABLE comment (
    comment_id INT AUTO_INCREMENT NOT NULL,
    article_id INT NOT NULL,
    commenter_id INT NOT NULL,
    body VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(0) DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(0) NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY (comment_id)
);
-- changeset liquibase-autogenerated:1733359107750-4
CREATE TABLE follower (
    user_id INT NOT NULL,
    follower_id INT NOT NULL,
    followed_at TIMESTAMP(0) DEFAULT NOW() NULL,
    CONSTRAINT PK_FOLLOWER PRIMARY KEY (user_id, follower_id)
);
-- changeset liquibase-autogenerated:1733359107750-5
CREATE TABLE tag (
    tag_id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TAG PRIMARY KEY (tag_id)
);
-- changeset liquibase-autogenerated:1733359107750-6
CREATE TABLE user (
    user_id INT AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password_hash VARCHAR(200) NOT NULL,
    bio TEXT NOT NULL,
    created_at TIMESTAMP(0) DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(0) NULL,
    CONSTRAINT PK_USER PRIMARY KEY (user_id)
);
-- changeset liquibase-autogenerated:1733359107750-7
CREATE INDEX article_fk_author ON article(author_id);
-- changeset liquibase-autogenerated:1733359107750-8
CREATE INDEX article_tag_fk_tag ON article_tag(tag_id);
-- changeset liquibase-autogenerated:1733359107750-9
CREATE INDEX comment_fk_article ON comment(article_id);
-- changeset liquibase-autogenerated:1733359107750-10
CREATE INDEX comment_fk_commenter ON comment(commenter_id);
-- changeset liquibase-autogenerated:1733359107750-11
CREATE INDEX follower_fk_follower ON follower(follower_id);
-- changeset liquibase-autogenerated:1733359107750-12
ALTER TABLE article
ADD CONSTRAINT article_fk_author FOREIGN KEY (author_id) REFERENCES user (user_id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- changeset liquibase-autogenerated:1733359107750-13
ALTER TABLE article_tag
ADD CONSTRAINT article_tag_fk_article FOREIGN KEY (article_id) REFERENCES article (article_id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- changeset liquibase-autogenerated:1733359107750-14
ALTER TABLE article_tag
ADD CONSTRAINT article_tag_fk_tag FOREIGN KEY (tag_id) REFERENCES tag (tag_id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- changeset liquibase-autogenerated:1733359107750-15
ALTER TABLE comment
ADD CONSTRAINT comment_fk_article FOREIGN KEY (article_id) REFERENCES article (article_id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- changeset liquibase-autogenerated:1733359107750-16
ALTER TABLE comment
ADD CONSTRAINT comment_fk_commenter FOREIGN KEY (commenter_id) REFERENCES user (user_id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- changeset liquibase-autogenerated:1733359107750-17
ALTER TABLE follower
ADD CONSTRAINT follower_fk_follower FOREIGN KEY (follower_id) REFERENCES user (user_id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- changeset liquibase-autogenerated:1733359107750-18
ALTER TABLE follower
ADD CONSTRAINT follower_fk_user FOREIGN KEY (user_id) REFERENCES user (user_id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- changeset scorbiclife:1 context:non-prod
INSERT INTO `user` (
        username,
        email,
        password_hash,
        bio,
        created_at,
        updated_at,
        deleted_at
    )
VALUES (
        'foo',
        'foo@example.com',
        'foo-hash',
        'hello, this is foo',
        '2024-12-02 03:39:02',
        '2024-12-02 03:39:02',
        NULL
    ),
    (
        'bar',
        'bar@example.com',
        'bar-hash',
        'Hello, I am bar.',
        '2024-12-02 03:39:02',
        '2024-12-02 03:39:02',
        NULL
    ),
    (
        'baz',
        'baz@example.com',
        'baz-hash',
        'hello my name is baz',
        '2024-12-02 04:17:20',
        '2024-12-02 04:17:20',
        NULL
    );
-- changeset scorbiclife:2 context:non-prod
INSERT INTO `article` (
        author_id,
        title,
        slug,
        description,
        body,
        created_at,
        updated_at,
        deleted_at
    )
VALUES (
        2,
        'first post',
        'first-post',
        'my first post',
        'This is my first post',
        '2024-12-03 01:07:29',
        '2024-12-03 01:07:29',
        NULL
    ),
    (
        1,
        'hello from foo',
        'hello-from-foo',
        '',
        'Hi, my name is foo and I like being example names.',
        '2024-12-03 01:07:29',
        '2024-12-03 01:07:29',
        NULL
    );